### ISSUE TITLE
World Switching Mechanic - Implement

### ISSUE THREAD

**Issue by libben** [libben/the-ocean#25]
See [this](https://docs.google.com/document/d/1Wz4ML8_ETgzms3SBv7tk3u9kqjYdgiWMUJKmj658s1Y) for up-to-date implementation requirements.

**Comment by lrcpwjno** [comment]
The version in branch "Mechanics-Implementation" now has checks to stop the player from switching into walls or objects in the other world. 

Still incomplete: extensive bug testing, switching in the underwater areas

**Comment by lrcpwjno** [comment]
Closing the issue as I think we have largely covered all our bases with world switching, including adding highlights for other-world blockages.
