### ISSUE TITLE
Prop Behavior - Implement

### ISSUE THREAD

**Issue by libben** [libben/the-ocean#40]
Implement [this](https://docs.google.com/document/d/1Ix7P-d9tIMOEcKCf9bwPNQ1RVJ8D5rBvKatW3-miliQ) behavior. Artwork is already done for everything but buttons.
- [x] Boxes
- [x] Buttons
- [x] Latchboxes (see #33 for description of what they look like on the ceiling)
- [x] Spikes

**Comment by lrcpwjno** [comment]
I've created prefabs for boxes and spikes in Assets/Prefabs using placeholder art (haven't yet resized our own assets). When placing them in the scene, don't forget to change their layer and sprite renderer sorting layer to match whichever layer it should be in.

**Boxes** are affected by physics but are too heavy to be pushed by the player unassisted. They have a controller with code to destroy the player if it hits the player with a certain velocity (should be tested in case boxes don't fall fast enough to kill when they should). Note: I haven't added gravity gun support yet.

**Spikes** are basically triangular trigger colliders that kill the player on contact. So far they'll kill you if you touch any part of them. To place them on the ceiling, probably just change y-scale to -1. Note: when we finalize the (set of) spikes art, we'll need to change the shape of the polygon collider on the prefab.

**Comment by lrcpwjno** [comment]
I've created prefabs for buttons and latchboxes using more placeholder art. (be sure to change all the sprite renderers' sprites to target the actual assets when they're finalized).

**Buttons** are 2 tiles wide (can be resized), sit on the floor, and get pushed down when something heavy like a player or box is placed on them. Don't forget to associate them with a latchbox in the inspector's serialized field.

**Latchboxes** can be placed anywhere, and have a trapdoor that opens when the associated button is stepped on. Right now they open instantly, but eventually they should play a little animation of the doors sliding apart or something.

All art is still placeholder.
